// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eliswotscxbzhhknoijm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsaXN3b3RzY3hiemhoa25vaWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDMxMzEsImV4cCI6MjA2MDcxOTEzMX0.CgUJB3fbJsHmfJ5LAfp8SP56hvZVnryrJhtR4FaWgu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);